apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-lwd-exporter
  labels:
    app.kubernetes.io/name: lwd-exporter
    app.kubernetes.io/part-of: shielded-stack
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: lwd-exporter
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lwd-exporter
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: lwd-exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SHIELDED_STACK_ADDR
              value: ":{{ .Values.service.port }}"
            - name: SHIELDED_STACK_ENDPOINTS
              value: "{{ join "," .Values.endpoints }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http

